### ISSUE TITLE
AWS timeout message

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-react#19]
Right now, just puts "TypeError: ..."

**Comment by jcruz** [comment]
The TypeError message comes from redux-saga failing to receive a response (see [here](https://github.com/cs121-team-panda/coconut-interpreter-react/blob/master/src/store/environment/saga.js#L17)). Instead of passing the error message we can just hardcode our own message instead. It can say `Error: early termination or timeout`. It is **not possible** to know which whether it's a timeout or not, except that the code was terminated.

Edit:
Actually I think this will be a #wontfix

**Comment by mjenrungrot** [comment]
Can we use time limit less than AWS limit on the backend and guarantee that the program will terminate, and the frontend will receive a response?

**Comment by jcruz** [comment]
The other edge case is if the backend isn't running then the error makes sense as `failed to fetch`.

**Comment by mjenrungrot** [comment]
Resolved by #33
